In [1]:
import pandas as pd 
import numpy as np

In [10]:
player_box = pd.read_csv("final_proj_data/basketball/Basketball-PlayerBoxScore.csv") 
box = pd.read_csv("final_proj_data/basketball/Basketball-BoxScores.csv") 
team_box = pd.read_csv("final_proj_data/basketball/Basketball-TeamBoxScores.csv") 
nba_standings = pd.read_csv("final_proj_data/basketball/Standings.csv") 
college = pd.read_csv("final_proj_data/basketball/college.csv")

In [12]:
data.head()
player_box.head()
box.head()
team_box.head()
nba_standings

,stDate,teamAbbr,rank,rankOrd,gameWon,gameLost,stk,stkType,stkTot,gameBack,...,rel%Indx,mov,srs,pw%,pyth%13.91,wpyth13.91,lpyth13.91,pyth%16.5,wpyth16.5,lpyth16.5
0,2012-10-30,ATL,3,3rd,0,0,-,-,0,0.5,...,0.000000,0.0000,0.0000,0.5000,0.0000,0.0000,82.0000,0.0000,0.0000,82.0000
1,2012-10-30,BKN,3,3rd,0,0,-,-,0,0.5,...,0.000000,0.0000,0.0000,0.5000,0.0000,0.0000,82.0000,0.0000,0.0000,82.0000
2,2012-10-30,BOS,14,14th,0,1,L1,loss,1,1.0,...,0.000000,-13.0000,-13.0000,0.0720,0.1687,13.8334,68.1666,0.1310,10.7420,71.2580
3,2012-10-30,CHA,3,3rd,0,0,-,-,0,0.5,...,0.000000,0.0000,0.0000,0.5000,0.0000,0.0000,82.0000,0.0000,0.0000,82.0000
4,2012-10-30,CHI,3,3rd,0,0,-,-,0,0.5,...,0.000000,0.0000,0.0000,0.5000,0.0000,0.0000,82.0000,0.0000,0.0000,82.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29515,2018-04-11,SA,7,7th,47,35,L1,loss,1,18.0,...,0.518525,2.8902,2.3899,0.5952,0.5980,49.0360,32.9640,0.6156,50.4792,31.5208
29516,2018-04-11,SAC,12,12th,27,55,W1,win,1,38.0,...,0.460225,-6.9878,-7.4917,0.2699,0.2788,22.8616,59.1384,0.2447,20.0654,61.9346
29517,2018-04-11,TOR,1,1st,59,23,L1,loss,1,0.0,...,0.550275,7.7439,7.2500,0.7550,0.7311,59.9502,22.0498,0.7661,62.8202,19.1798
29518,2018-04-11,UTA,4,4th,48,34,L1,loss,1,17.0,...,0.526425,4.3049,3.7981,0.6417,0.6427,52.7014,29.2986,0.6674,54.7268,27.2732
29519,2018-04-11,WAS,8,8th,43,39,L1,loss,1,16.0,...,0.506125,0.5854,0.0854,0.5193,0.5191,42.5662,39.4338,0.5227,42.8614,39.1386

In [ ]:
college["college"]